api_platform:
    defaults:
        pagination_enabled: false
    formats:
        multipart: ['multipart/form-data']
        jsonld: ['application/ld+json']
    use_symfony_listeners: true
    serializer:
        hydra_prefix: true